language: python
python:
- '3.6'
- '3.7'
- '3.8'
install:
- pip install -U pycodestyle
- pip install -U setuptools
- python setup.py install
script:
- pycodestyle --max-line-length=100 starred
- starred --username 1132719438